# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateMatC <- function(M, add_row, add_col, remove_row, remove_col, hhsize, hhid) {
    .Call('_simPop_updateMatC', PACKAGE = 'simPop', M, add_row, add_col, remove_row, remove_col, hhsize, hhid)
}

updateVecC <- function(init_weight, add_index, remove_index, hhsize, hhid, sizefactor) {
    .Call('_simPop_updateVecC', PACKAGE = 'simPop', init_weight, add_index, remove_index, hhsize, hhid, sizefactor)
}

sumVec <- function(init_weight, sizefactor) {
    .Call('_simPop_sumVec', PACKAGE = 'simPop', init_weight, sizefactor)
}

select_equal <- function(x, val1, val2) {
    .Call('_simPop_select_equal', PACKAGE = 'simPop', x, val1, val2)
}

tableC <- function(x) {
    .Call('_simPop_tableC', PACKAGE = 'simPop', x)
}

csample_num <- function(x, size, replace, prob = as.numeric( c())) {
    .Call('_simPop_csample_num', PACKAGE = 'simPop', x, size, replace, prob)
}

sample_group <- function(x, group_x, group, group_num, replace) {
    .Call('_simPop_sample_group', PACKAGE = 'simPop', x, group_x, group, group_num, replace)
}

